# Generated by Django 5.2.6 on 2025-09-28 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls order in multi-step voting')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_nomination', models.DateTimeField()),
                ('end_nomination', models.DateTimeField()),
                ('start_voting', models.DateTimeField()),
                ('end_voting', models.DateTimeField()),
                ('nomination_open', models.BooleanField(default=False)),
                ('voting_open', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Nominations Open', 'Nominations Open'), ('Voting Open', 'Voting Open'), ('Closed', 'Closed')], default='Nominations Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('nominee', 'Nominee Form'), ('voter', 'Voter Form')], max_length=10)),
                ('field_name', models.CharField(max_length=50)),
                ('label_text', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('form_type', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('workplace_address', models.CharField(max_length=255)),
                ('interested', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desired_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.position')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.session')),
            ],
            options={
                'unique_together': {('session', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('workplace_address', models.CharField(max_length=255)),
                ('last_training_date', models.DateField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.session')),
            ],
            options={
                'unique_together': {('session', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.nomination')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.position')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.session')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.voter')),
            ],
            options={
                'unique_together': {('voter', 'position')},
            },
        ),
    ]
