# Generated by Django 5.2.6 on 2025-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='last_training_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
