# Generated by Django 5.2.6 on 2025-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_nomination_last_training_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Nominations Open', 'Nominations Open'), ('Voting Open', 'Voting Open'), ('Results Published', 'Results Published'), ('Closed', 'Closed')], default='Nominations Open', max_length=20),
        ),
    ]
